# Generated by Django 3.2.9 on 2021-12-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='result_player1',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='result_player2',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
