# Generated by Django 3.2.9 on 2022-01-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='result_easy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='result_hard',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='result_medium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='result_multiplayer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='result1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='result2',
            field=models.FloatField(),
        ),
    ]
