# Generated by Django 3.2.9 on 2021-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
