# Generated by Django 3.2.9 on 2021-12-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211225_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
